// -------------------------------------------------------------------------------------------------------------------------- //
// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Francisco Romano
// -------------------------------------------------------------------------------------------------------------------------- //
#ifndef __core_linux_libX11_h__
#define __core_linux_libX11_h__
#ifdef __cplusplus
extern "C" {
#endif
// -------------------------------------------------------------------------------------------------------------------------- //

#include "../public.h"
#include "libX11/keysym.h"
#include "libX11/keysymdef.h"
#include "libX11/X.h"
#include "libX11/Xatom.h"
#include "libX11/Xlib.h"
#include "libX11/Xutil.h"

// -------------------------------------------------------------------------------------------------------------------------- //

DECLARE_LIBRARY(libX11,
    // #include <X11/Xlib.h>
    int32_t              (*_Xmblen)(char*,int32_t);
    int32_t              (*_Xmbtowc)(wchar_t*,char*,int32_t);
    int32_t              (*_Xwctomb)(char*,wchar_t);
    int32_t              (*XActivateScreenSaver)(XDisplay*);
    int32_t              (*XAddConnectionWatch)(XDisplay*,XConnectionWatchProc,void*);
    XExtCodes*           (*XAddExtension)(XDisplay*);
    int32_t              (*XAddHost)(XDisplay*,XHostAddress*);
    int32_t              (*XAddHosts)(XDisplay*,XHostAddress*,int32_t);
    int32_t              (*XAddToExtensionList)(XExtData**,XExtData*);
    int32_t              (*XAddToSaveSet)(XDisplay*,XWindow);
    int32_t              (*XAllocColor)(XDisplay*,XColormap,XColor*);
    int32_t              (*XAllocColorCells)(XDisplay*,XColormap,int32_t,uint32_t*,uint32_t,uint32_t*,uint32_t);
    int32_t              (*XAllocColorPlanes)(XDisplay*,XColormap,int32_t,uint32_t*,int32_t,int32_t,int32_t,int32_t,uint32_t*,uint32_t*,uint32_t*);
    int32_t              (*XAllocNamedColor)(XDisplay*,XColormap,const char*,XColor*,XColor*);
    int32_t              (*XAllowEvents)(XDisplay*,int32_t,XTime);
    uint32_t             (*XAllPlanes)();
    int32_t              (*XAutoRepeatOff)(XDisplay*);
    int32_t              (*XAutoRepeatOn)(XDisplay*);
    char*                (*XBaseFontNameListOfFontSet)(XFontSet);
    int32_t              (*XBell)(XDisplay*,int32_t);
    int32_t              (*XBitmapBitOrder)(XDisplay*);
    int32_t              (*XBitmapPad)(XDisplay*);
    int32_t              (*XBitmapUnit)(XDisplay*);
    uint32_t             (*XBlackPixel)(XDisplay*,int32_t);
    uint32_t             (*XBlackPixelOfScreen)(XScreen*);
    int32_t              (*XCellsOfScreen)(XScreen*);
    int32_t              (*XChangeActivePointerGrab)(XDisplay*,uint32_t,XCursor,XTime);
    int32_t              (*XChangeGC)(XDisplay*,XGC,uint32_t,XGCValues*);
    int32_t              (*XChangeKeyboardControl)(XDisplay*,uint32_t,XKeyboardControl*);
    int32_t              (*XChangeKeyboardMapping)(XDisplay*,int32_t,int32_t,XKeySym*,int32_t);
    int32_t              (*XChangePointerControl)(XDisplay*,int32_t,int32_t,int32_t,int32_t,int32_t);
    int32_t              (*XChangeProperty)(XDisplay*,XWindow,XAtom,XAtom,int32_t,int32_t,const uint8_t*,int32_t);
    int32_t              (*XChangeSaveSet)(XDisplay*,XWindow,int32_t);
    int32_t              (*XChangeWindowAttributes)(XDisplay*,XWindow,uint32_t,XSetWindowAttributes*);
    int32_t              (*XCheckIfEvent)(XDisplay*,XEvent*,int32_t(*)(XDisplay*,XEvent*,void*),void*);
    int32_t              (*XCheckMaskEvent)(XDisplay*,int32_t,XEvent*);
    int32_t              (*XCheckTypedEvent)(XDisplay*,int32_t,XEvent*);
    int32_t              (*XCheckTypedWindowEvent)(XDisplay*,XWindow,int32_t,XEvent*);
    int32_t              (*XCheckWindowEvent)(XDisplay*,XWindow,int32_t,XEvent*);
    int32_t              (*XCirculateSubwindows)(XDisplay*,XWindow,int32_t);
    int32_t              (*XCirculateSubwindowsDown)(XDisplay*,XWindow);
    int32_t              (*XCirculateSubwindowsUp)(XDisplay*,XWindow);
    int32_t              (*XClearArea)(XDisplay*,XWindow,int32_t,int32_t,uint32_t,uint32_t,int32_t);
    int32_t              (*XClearWindow)(XDisplay*,XWindow);
    int32_t              (*XCloseDisplay)(XDisplay*);
    int32_t              (*XCloseIM)(XIM);
    int32_t              (*XCloseOM)(XOM);
    int32_t              (*XConfigureWindow)(XDisplay*,XWindow,uint32_t,XWindowChanges*);
    int32_t              (*XConnectionNumber)(XDisplay*);
    int32_t              (*XContextDependentDrawing)(XFontSet);
    int32_t              (*XContextualDrawing)(XFontSet);
    int32_t              (*XConvertSelection)(XDisplay*,XAtom,XAtom,XAtom,XWindow,XTime);
    int32_t              (*XCopyArea)(XDisplay*,XDrawable,XDrawable,XGC,int32_t,int32_t,uint32_t,uint32_t,int32_t,int32_t);
    XColormap            (*XCopyColormapAndFree)(XDisplay*,XColormap);
    int32_t              (*XCopyGC)(XDisplay*,XGC,uint32_t,XGC);
    int32_t              (*XCopyPlane)(XDisplay*,XDrawable,XDrawable,XGC,int32_t,int32_t,uint32_t,uint32_t,int32_t,int32_t,uint32_t);
    XPixmap              (*XCreateBitmapFromData)(XDisplay*,XDrawable,const char*,uint32_t,uint32_t);
    XColormap            (*XCreateColormap)(XDisplay*,XWindow,XVisual*,int32_t);
    XCursor              (*XCreateFontCursor)(XDisplay*,uint32_t);
    XFontSet             (*XCreateFontSet)(XDisplay*,const char*,char***,int32_t*,char**);
    XGC                  (*XCreateGC)(XDisplay*,XDrawable,uint32_t,XGCValues*);
    XCursor              (*XCreateGlyphCursor)(XDisplay*,XFont,XFont,uint32_t,uint32_t,XColor const*,XColor const*);
    XIC                  (*XCreateIC)(XIM,...);
    XImage*              (*XCreateImage)(XDisplay*,XVisual*,uint32_t,int32_t,int32_t,char*,uint32_t,uint32_t,int32_t,int32_t);
    XOC                  (*XCreateOC)(XOM,...);
    XPixmap              (*XCreatePixmap)(XDisplay*,XDrawable,uint32_t,uint32_t,uint32_t);
    XCursor              (*XCreatePixmapCursor)(XDisplay*,XPixmap,XPixmap,XColor*,XColor*,uint32_t,uint32_t);
    XPixmap              (*XCreatePixmapFromBitmapData)(XDisplay*,XDrawable,char*,uint32_t,uint32_t,uint32_t,uint32_t,uint32_t);
    XWindow              (*XCreateSimpleWindow)(XDisplay*,XWindow,int32_t,int32_t,uint32_t,uint32_t,uint32_t,uint32_t,uint32_t);
    XWindow              (*XCreateWindow)(XDisplay*,XWindow,int32_t,int32_t,uint32_t,uint32_t,uint32_t,int32_t,uint32_t,XVisual*,uint32_t,XSetWindowAttributes*);
    XColormap            (*XDefaultColormap)(XDisplay*,int32_t);
    XColormap            (*XDefaultColormapOfScreen)(XScreen*);
    int32_t              (*XDefaultDepth)(XDisplay*,int32_t);
    int32_t              (*XDefaultDepthOfScreen)(XScreen*);
    XGC                  (*XDefaultGC)(XDisplay*,int32_t);
    XGC                  (*XDefaultGCOfScreen)(XScreen*);
    XWindow              (*XDefaultRootWindow)(XDisplay*);
    int32_t              (*XDefaultScreen)(XDisplay*);
    XScreen*             (*XDefaultScreenOfDisplay)(XDisplay*);
    XVisual*             (*XDefaultVisual)(XDisplay*,int32_t);
    XVisual*             (*XDefaultVisualOfScreen)(XScreen*);
    int32_t              (*XDefineCursor)(XDisplay*,XWindow,XCursor);
    XModifierKeymap*     (*XDeleteModifiermapEntry)(XModifierKeymap*,XKeyCode,int32_t);
    int32_t              (*XDeleteProperty)(XDisplay*,XWindow,XAtom);
    void                 (*XDestroyIC)(XIC);
    void                 (*XDestroyOC)(XOC);
    int32_t              (*XDestroySubwindows)(XDisplay*,XWindow);
    int32_t              (*XDestroyWindow)(XDisplay*,XWindow);
    int32_t              (*XDirectionalDependentDrawing)(XFontSet);
    int32_t              (*XDisableAccessControl)(XDisplay*);
    int32_t              (*XDisplayCells)(XDisplay*,int32_t);
    int32_t              (*XDisplayHeight)(XDisplay*,int32_t);
    int32_t              (*XDisplayHeightMM)(XDisplay*,int32_t);
    int32_t              (*XDisplayKeycodes)(XDisplay*,int32_t*,int32_t*);
    uint32_t             (*XDisplayMotionBufferSize)(XDisplay*);
    char*                (*XDisplayName)(const char*);
    XDisplay*            (*XDisplayOfIM)(XIM);
    XDisplay*            (*XDisplayOfOM)(XOM);
    XDisplay*            (*XDisplayOfScreen)(XScreen*);
    int32_t              (*XDisplayPlanes)(XDisplay*,int32_t);
    char*                (*XDisplayString)(XDisplay*);
    int32_t              (*XDisplayWidth)(XDisplay*,int32_t);
    int32_t              (*XDisplayWidthMM)(XDisplay*,int32_t);
    int32_t              (*XDoesBackingStore)(XScreen*);
    int32_t              (*XDoesSaveUnders)(XScreen*);
    int32_t              (*XDrawArc)(XDisplay*,XDrawable,XGC,int32_t,int32_t,uint32_t,uint32_t,int32_t,int32_t);
    int32_t              (*XDrawArcs)(XDisplay*,XDrawable,XGC,XArc*,int32_t);
    int32_t              (*XDrawImageString)(XDisplay*,XDrawable,XGC,int32_t,int32_t,const char*,int32_t);
    int32_t              (*XDrawImageString16)(XDisplay*,XDrawable,XGC,int32_t,int32_t,const XChar2b*,int32_t);
    int32_t              (*XDrawLine)(XDisplay*,XDrawable,XGC,int32_t,int32_t,int32_t,int32_t);
    int32_t              (*XDrawLines)(XDisplay*,XDrawable,XGC,XPoint*,int32_t,int32_t);
    int32_t              (*XDrawPoint)(XDisplay*,XDrawable,XGC,int32_t,int32_t);
    int32_t              (*XDrawPoints)(XDisplay*,XDrawable,XGC,XPoint*,int32_t,int32_t);
    int32_t              (*XDrawRectangle)(XDisplay*,XDrawable,XGC,int32_t,int32_t,uint32_t,uint32_t);
    int32_t              (*XDrawRectangles)(XDisplay*,XDrawable,XGC,XRectangle*,int32_t);
    int32_t              (*XDrawSegments)(XDisplay*,XDrawable,XGC,XSegment*,int32_t);
    int32_t              (*XDrawString)(XDisplay*,XDrawable,XGC,int32_t,int32_t,const char*,int32_t);
    int32_t              (*XDrawString16)(XDisplay*,XDrawable,XGC,int32_t,int32_t,const XChar2b*,int32_t);
    int32_t              (*XDrawText)(XDisplay*,XDrawable,XGC,int32_t,int32_t,XTextItem*,int32_t);
    int32_t              (*XDrawText16)(XDisplay*,XDrawable,XGC,int32_t,int32_t,XTextItem16*,int32_t);
    XExtData**           (*XEHeadOfExtensionList)(XEDataObject);
    int32_t              (*XEnableAccessControl)(XDisplay*);
    int32_t              (*XEventMaskOfScreen)(XScreen*);
    int32_t              (*XEventsQueued)(XDisplay*,int32_t);
    int32_t              (*XExtendedMaxRequestSize)(XDisplay*);
    XFontSetExtents*     (*XExtentsOfFontSet)(XFontSet);
    char*                (*XFetchBuffer)(XDisplay*,int32_t*,int32_t);
    char*                (*XFetchBytes)(XDisplay*,int32_t*);
    int32_t              (*XFetchName)(XDisplay*,XWindow,char**);
    int32_t              (*XFillArc)(XDisplay*,XDrawable,XGC,int32_t,int32_t,uint32_t,uint32_t,int32_t,int32_t);
    int32_t              (*XFillArcs)(XDisplay*,XDrawable,XGC,XArc*,int32_t);
    int32_t              (*XFillPolygon)(XDisplay*,XDrawable,XGC,XPoint*,int32_t,int32_t,int32_t);
    int32_t              (*XFillRectangle)(XDisplay*,XDrawable,XGC,int32_t,int32_t,uint32_t,uint32_t);
    int32_t              (*XFillRectangles)(XDisplay*,XDrawable,XGC,XRectangle*,int32_t);
    int32_t              (*XFilterEvent)(XEvent*,XWindow);
    XExtData*            (*XFindOnExtensionList)(XExtData**,int32_t);
    int32_t              (*XFlush)(XDisplay*);
    void                 (*XFlushGC)(XDisplay*,XGC);
    int32_t              (*XFontsOfFontSet)(XFontSet,XFontStruct***,char***);
    int32_t              (*XForceScreenSaver)(XDisplay*,int32_t);
    int32_t              (*XFree)(void*);
    int32_t              (*XFreeColormap)(XDisplay*,XColormap);
    int32_t              (*XFreeColors)(XDisplay*,XColormap,uint32_t*,int32_t,uint32_t);
    int32_t              (*XFreeCursor)(XDisplay*,XCursor);
    void                 (*XFreeEventData)(XDisplay*,XGenericEventCookie*);
    int32_t              (*XFreeExtensionList)(char**);
    int32_t              (*XFreeFont)(XDisplay*,XFontStruct*);
    int32_t              (*XFreeFontInfo)(char**,XFontStruct*,int32_t);
    int32_t              (*XFreeFontNames)(char**);
    int32_t              (*XFreeFontPath)(char**);
    void                 (*XFreeFontSet)(XDisplay*,XFontSet);
    int32_t              (*XFreeGC)(XDisplay*,XGC);
    int32_t              (*XFreeModifiermap)(XModifierKeymap*);
    int32_t              (*XFreePixmap)(XDisplay*,XPixmap);
    void                 (*XFreeStringList)(char**);
    int32_t              (*XFreeThreads)();
    XGContext            (*XGContextFromGC)(XGC);
    int32_t              (*XGeometry)(XDisplay*,int32_t,const char*,const char*,uint32_t,uint32_t,uint32_t,int32_t,int32_t,int32_t*,int32_t*,int32_t*,int32_t*);
    char*                (*XGetAtomName)(XDisplay*,XAtom);
    int32_t              (*XGetAtomNames)(XDisplay*,XAtom*,int32_t,char**);
    int32_t              (*XGetCommand)(XDisplay*,XWindow,char***,int32_t*);
    char*                (*XGetDefault)(XDisplay*,const char*,const char*);
    int32_t              (*XGetErrorDatabaseText)(XDisplay*,const char*,const char*,const char*,char*,int32_t);
    int32_t              (*XGetErrorText)(XDisplay*,int32_t,char*,int32_t);
    int32_t              (*XGetEventData)(XDisplay*,XGenericEventCookie*);
    char**               (*XGetFontPath)(XDisplay*,int32_t*);
    int32_t              (*XGetFontProperty)(XFontStruct*,XAtom,uint32_t*);
    int32_t              (*XGetGCValues)(XDisplay*,XGC,uint32_t,XGCValues*);
    int32_t              (*XGetGeometry)(XDisplay*,XDrawable,XWindow*,int32_t*,int32_t*,uint32_t*,uint32_t*,uint32_t*,uint32_t*);
    int32_t              (*XGetIconName)(XDisplay*,XWindow,char**);
    char*                (*XGetICValues)(XIC,...);
    XImage*              (*XGetImage)(XDisplay*,XDrawable,int32_t,int32_t,uint32_t,uint32_t,uint32_t,int32_t);
    char*                (*XGetIMValues)(XIM,...);
    int32_t              (*XGetInputFocus)(XDisplay*,XWindow*,int32_t*);
    int32_t              (*XGetKeyboardControl)(XDisplay*,XKeyboardState*);
    XKeySym*             (*XGetKeyboardMapping)(XDisplay*,XKeyCode,int32_t,int32_t*);
    XModifierKeymap*     (*XGetModifierMapping)(XDisplay*);
    XTimeCoord*          (*XGetMotionEvents)(XDisplay*,XWindow,XTime,XTime,int32_t*);
    char*                (*XGetOCValues)(XOC,...);
    char*                (*XGetOMValues)(XOM,...);
    int32_t              (*XGetPointerControl)(XDisplay*,int32_t*,int32_t*,int32_t*);
    int32_t              (*XGetPointerMapping)(XDisplay*,uint8_t*,int32_t);
    int32_t              (*XGetScreenSaver)(XDisplay*,int32_t*,int32_t*,int32_t*,int32_t*);
    XWindow              (*XGetSelectionOwner)(XDisplay*,XAtom);
    XImage*              (*XGetSubImage)(XDisplay*,XDrawable,int32_t,int32_t,uint32_t,uint32_t,uint32_t,int32_t,XImage*,int32_t,int32_t);
    int32_t              (*XGetTransientForHint)(XDisplay*,XWindow,XWindow*);
    int32_t              (*XGetWindowAttributes)(XDisplay*,XWindow,XWindowAttributes*);
    int32_t              (*XGetWindowProperty)(XDisplay*,XWindow,XAtom,int32_t,int32_t,int32_t,XAtom,XAtom*,int32_t*,uint32_t*,uint32_t*,uint8_t**);
    int32_t              (*XGetWMColormapWindows)(XDisplay*,XWindow,XWindow**,int32_t*);
    int32_t              (*XGetWMProtocols)(XDisplay*,XWindow,XAtom**,int32_t*);
    int32_t              (*XGrabButton)(XDisplay*,uint32_t,uint32_t,XWindow,int32_t,uint32_t,int32_t,int32_t,XWindow,XCursor);
    int32_t              (*XGrabKey)(XDisplay*,int32_t,uint32_t,XWindow,int32_t,int32_t,int32_t);
    int32_t              (*XGrabKeyboard)(XDisplay*,XWindow,int32_t,int32_t,int32_t,XTime);
    int32_t              (*XGrabPointer)(XDisplay*,XWindow,int32_t,uint32_t,int32_t,int32_t,XWindow,XCursor,XTime);
    int32_t              (*XGrabServer)(XDisplay*);
    int32_t              (*XHeightMMOfScreen)(XScreen*);
    int32_t              (*XHeightOfScreen)(XScreen*);
    int32_t              (*XIconifyWindow)(XDisplay*,XWindow,int32_t);
    int32_t              (*XIfEvent)(XDisplay*,XEvent*,int32_t(*)(XDisplay*,XEvent*,void*),void*);
    int32_t              (*XImageByteOrder)(XDisplay*);
    XIM                  (*XIMOfIC)(XIC);
    XExtCodes*           (*XInitExtension)(XDisplay*,const char*);
    int32_t              (*XInitImage)(XImage*);
    int32_t              (*XInitThreads)();
    XModifierKeymap*     (*XInsertModifiermapEntry)(XModifierKeymap*,XKeyCode,int32_t);
    int32_t              (*XInstallColormap)(XDisplay*,XColormap);
    int32_t              (*XInternalConnectionNumbers)(XDisplay*,int32_t**,int32_t*);
    XAtom                (*XInternAtom)(XDisplay*,const char*,int32_t);
    int32_t              (*XInternAtoms)(XDisplay*,char**,int32_t,int32_t,XAtom*);
    XKeySym              (*XKeycodeToKeysym)(XDisplay*,XKeyCode,int32_t);
    XKeyCode             (*XKeysymToKeycode)(XDisplay*,XKeySym);
    char*                (*XKeysymToString)(XKeySym);
    int32_t              (*XKillClient)(XDisplay*,XID);
    uint32_t             (*XLastKnownRequestProcessed)(XDisplay*);
    int32_t*             (*XListDepths)(XDisplay*,int32_t,int32_t*);
    char**               (*XListExtensions)(XDisplay*,int32_t*);
    char**               (*XListFonts)(XDisplay*,const char*,int32_t,int32_t*);
    char**               (*XListFontsWithInfo)(XDisplay*,const char*,int32_t,int32_t*,XFontStruct**);
    XHostAddress*        (*XListHosts)(XDisplay*,int32_t*,int32_t*);
    XColormap*           (*XListInstalledColormaps)(XDisplay*,XWindow,int32_t*);
    XPixmapFormatValues* (*XListPixmapFormats)(XDisplay*,int32_t*);
    XAtom*               (*XListProperties)(XDisplay*,XWindow,int32_t*);
    XFont                (*XLoadFont)(XDisplay*,const char*);
    XFontStruct*         (*XLoadQueryFont)(XDisplay*,const char*);
    char*                (*XLocaleOfFontSet)(XFontSet);
    char*                (*XLocaleOfIM)(XIM);
    char*                (*XLocaleOfOM)(XOM);
    void                 (*XLockDisplay)(XDisplay*);
    int32_t              (*XLookupColor)(XDisplay*,XColormap,const char*,XColor*,XColor*);
    XKeySym              (*XLookupKeysym)(XKeyEvent*,int32_t);
    int32_t              (*XLowerWindow)(XDisplay*,XWindow);
    int32_t              (*XMapRaised)(XDisplay*,XWindow);
    int32_t              (*XMapSubwindows)(XDisplay*,XWindow);
    int32_t              (*XMapWindow)(XDisplay*,XWindow);
    int32_t              (*XMaskEvent)(XDisplay*,int32_t,XEvent*);
    int32_t              (*XMaxCmapsOfScreen)(XScreen*);
    int32_t              (*XMaxRequestSize)(XDisplay*);
    void                 (*XmbDrawImageString)(XDisplay*,XDrawable,XFontSet,XGC,int32_t,int32_t,const char*,int32_t);
    void                 (*XmbDrawString)(XDisplay*,XDrawable,XFontSet,XGC,int32_t,int32_t,const char*,int32_t);
    void                 (*XmbDrawText)(XDisplay*,XDrawable,XGC,int32_t,int32_t,XmbTextItem*,int32_t);
    int32_t              (*XmbLookupString)(XIC,XKeyEvent*,char*,int32_t,XKeySym*,int32_t*);
    char*                (*XmbResetIC)(XIC);
    int32_t              (*XmbTextEscapement)(XFontSet,const char*,int32_t);
    int32_t              (*XmbTextExtents)(XFontSet,const char*,int32_t,XRectangle*,XRectangle*);
    int32_t              (*XmbTextPerCharExtents)(XFontSet,const char*,int32_t,XRectangle*,XRectangle*,int32_t,int32_t*,XRectangle*,XRectangle*);
    int32_t              (*XMinCmapsOfScreen)(XScreen*);
    int32_t              (*XMoveResizeWindow)(XDisplay*,XWindow,int32_t,int32_t,uint32_t,uint32_t);
    int32_t              (*XMoveWindow)(XDisplay*,XWindow,int32_t,int32_t);
    XModifierKeymap*     (*XNewModifiermap)(int32_t);
    int32_t              (*XNextEvent)(XDisplay*,XEvent*);
    uint32_t             (*XNextRequest)(XDisplay*);
    int32_t              (*XNoOp)(XDisplay*);
    XOM                  (*XOMOfOC)(XOC);
    XDisplay*            (*XOpenDisplay)(const char*);
    XIM                  (*XOpenIM)(XDisplay*,XrmHashBucketRec*,char*,char*);
    XOM                  (*XOpenOM)(XDisplay*,XrmHashBucketRec*,const char*,const char*);
    int32_t              (*XParseColor)(XDisplay*,XColormap,const char*,XColor*);
    int32_t              (*XParseGeometry)(const char*,int32_t*,int32_t*,uint32_t*,uint32_t*);
    int32_t              (*XPeekEvent)(XDisplay*,XEvent*);
    int32_t              (*XPeekIfEvent)(XDisplay*,XEvent*,int32_t(*)(XDisplay*,XEvent*,void*),void*);
    int32_t              (*XPending)(XDisplay*);
    int32_t              (*XPlanesOfScreen)(XScreen*);
    void                 (*XProcessInternalConnection)(XDisplay*,int32_t);
    int32_t              (*XProtocolRevision)(XDisplay*);
    int32_t              (*XProtocolVersion)(XDisplay*);
    int32_t              (*XPutBackEvent)(XDisplay*,XEvent*);
    int32_t              (*XPutImage)(XDisplay*,XDrawable,XGC,XImage*,int32_t,int32_t,int32_t,int32_t,uint32_t,uint32_t);
    int32_t              (*XQLength)(XDisplay*);
    int32_t              (*XQueryBestCursor)(XDisplay*,XDrawable,uint32_t,uint32_t,uint32_t*,uint32_t*);
    int32_t              (*XQueryBestSize)(XDisplay*,int32_t,XDrawable,uint32_t,uint32_t,uint32_t*,uint32_t*);
    int32_t              (*XQueryBestStipple)(XDisplay*,XDrawable,uint32_t,uint32_t,uint32_t*,uint32_t*);
    int32_t              (*XQueryBestTile)(XDisplay*,XDrawable,uint32_t,uint32_t,uint32_t*,uint32_t*);
    int32_t              (*XQueryColor)(XDisplay*,XColormap,XColor*);
    int32_t              (*XQueryColors)(XDisplay*,XColormap,XColor*,int32_t);
    int32_t              (*XQueryExtension)(XDisplay*,const char*,int32_t*,int32_t*,int32_t*);
    XFontStruct*         (*XQueryFont)(XDisplay*,XID);
    int32_t              (*XQueryKeymap)(XDisplay*,char[32]);
    int32_t              (*XQueryPointer)(XDisplay*,XWindow,XWindow*,XWindow*,int32_t*,int32_t*,int32_t*,int32_t*,uint32_t*);
    int32_t              (*XQueryTextExtents)(XDisplay*,XID,const char*,int32_t,int32_t*,int32_t*,int32_t*,XCharStruct*);
    int32_t              (*XQueryTextExtents16)(XDisplay*,XID,const XChar2b*,int32_t,int32_t*,int32_t*,int32_t*,XCharStruct*);
    int32_t              (*XQueryTree)(XDisplay*,XWindow,XWindow*,XWindow*,XWindow**,uint32_t*);
    int32_t              (*XRaiseWindow)(XDisplay*,XWindow);
    int32_t              (*XReadBitmapFile)(XDisplay*,XDrawable,const char*,uint32_t*,uint32_t*,XPixmap*,int32_t*,int32_t*);
    int32_t              (*XReadBitmapFileData)(const char*,uint32_t*,uint32_t*,uint8_t**,int32_t*,int32_t*);
    int32_t              (*XRebindKeysym)(XDisplay*,XKeySym,XKeySym*,int32_t,const uint8_t*,int32_t);
    int32_t              (*XRecolorCursor)(XDisplay*,XCursor,XColor*,XColor*);
    int32_t              (*XReconfigureWMWindow)(XDisplay*,XWindow,int32_t,uint32_t,XWindowChanges*);
    int32_t              (*XRefreshKeyboardMapping)(XMappingEvent*);
    int32_t              (*XRegisterIMInstantiateCallback)(XDisplay*,XrmHashBucketRec*,char*,char*,XIDProc,void*);
    void                 (*XRemoveConnectionWatch)(XDisplay*,XConnectionWatchProc,void*);
    int32_t              (*XRemoveFromSaveSet)(XDisplay*,XWindow);
    int32_t              (*XRemoveHost)(XDisplay*,XHostAddress*);
    int32_t              (*XRemoveHosts)(XDisplay*,XHostAddress*,int32_t);
    int32_t              (*XReparentWindow)(XDisplay*,XWindow,XWindow,int32_t,int32_t);
    int32_t              (*XResetScreenSaver)(XDisplay*);
    int32_t              (*XResizeWindow)(XDisplay*,XWindow,uint32_t,uint32_t);
    char*                (*XResourceManagerString)(XDisplay*);
    int32_t              (*XRestackWindows)(XDisplay*,XWindow*,int32_t);
    void                 (*XrmInitialize)();
    int                  (*XrmUniqueQuark)();
    XWindow              (*XRootWindow)(XDisplay*,int32_t);
    XWindow              (*XRootWindowOfScreen)(XScreen*);
    int32_t              (*XRotateBuffers)(XDisplay*,int32_t);
    int32_t              (*XRotateWindowProperties)(XDisplay*,XWindow,XAtom*,int32_t,int32_t);
    int32_t              (*XScreenCount)(XDisplay*);
    int32_t              (*XScreenNumberOfScreen)(XScreen*);
    XScreen*             (*XScreenOfDisplay)(XDisplay*,int32_t);
    char*                (*XScreenResourceString)(XScreen*);
    int32_t              (*XSelectInput)(XDisplay*,XWindow,int32_t);
    int32_t              (*XSendEvent)(XDisplay*,XWindow,int32_t,int32_t,XEvent*);
    char*                (*XServerVendor)(XDisplay*);
    int32_t              (*XSetAccessControl)(XDisplay*,int32_t);
    int32_t              (*XSetArcMode)(XDisplay*,XGC,int32_t);
    void                 (*XSetAuthorization)(char*,int32_t,char*,int32_t);
    int32_t              (*XSetBackground)(XDisplay*,XGC,uint32_t);
    int32_t              (*XSetClipMask)(XDisplay*,XGC,XPixmap);
    int32_t              (*XSetClipOrigin)(XDisplay*,XGC,int32_t,int32_t);
    int32_t              (*XSetClipRectangles)(XDisplay*,XGC,int32_t,int32_t,XRectangle*,int32_t,int32_t);
    int32_t              (*XSetCloseDownMode)(XDisplay*,int32_t);
    int32_t              (*XSetCommand)(XDisplay*,XWindow,char**,int32_t);
    int32_t              (*XSetDashes)(XDisplay*,XGC,int32_t,const char*,int32_t);
    XErrorHandler        (*XSetErrorHandler)(XErrorHandler);
    int32_t              (*XSetFillRule)(XDisplay*,XGC,int32_t);
    int32_t              (*XSetFillStyle)(XDisplay*,XGC,int32_t);
    int32_t              (*XSetFont)(XDisplay*,XGC,XFont);
    int32_t              (*XSetFontPath)(XDisplay*,char**,int32_t);
    int32_t              (*XSetForeground)(XDisplay*,XGC,uint32_t);
    int32_t              (*XSetFunction)(XDisplay*,XGC,int32_t);
    int32_t              (*XSetGraphicsExposures)(XDisplay*,XGC,int32_t);
    void                 (*XSetICFocus)(XIC);
    int32_t              (*XSetIconName)(XDisplay*,XWindow,const char*);
    char*                (*XSetICValues)(XIC,...);
    char*                (*XSetIMValues)(XIM,...);
    int32_t              (*XSetInputFocus)(XDisplay*,XWindow,int32_t,XTime);
    void                 (*XSetIOErrorExitHandler)(XDisplay*,XIOErrorExitHandler,void*);
    XIOErrorHandler      (*XSetIOErrorHandler)(XIOErrorHandler);
    int32_t              (*XSetLineAttributes)(XDisplay*,XGC,uint32_t,int32_t,int32_t,int32_t);
    char*                (*XSetLocaleModifiers)(const char*);
    int32_t              (*XSetModifierMapping)(XDisplay*,XModifierKeymap*);
    char*                (*XSetOCValues)(XOC,...);
    char*                (*XSetOMValues)(XOM,...);
    int32_t              (*XSetPlaneMask)(XDisplay*,XGC,uint32_t);
    int32_t              (*XSetPointerMapping)(XDisplay*,const uint8_t*,int32_t);
    int32_t              (*XSetScreenSaver)(XDisplay*,int32_t,int32_t,int32_t,int32_t);
    int32_t              (*XSetSelectionOwner)(XDisplay*,XAtom,XWindow,XTime);
    int32_t              (*XSetState)(XDisplay*,XGC,uint32_t,uint32_t,int32_t,uint32_t);
    int32_t              (*XSetStipple)(XDisplay*,XGC,XPixmap);
    int32_t              (*XSetSubwindowMode)(XDisplay*,XGC,int32_t);
    int32_t              (*XSetTile)(XDisplay*,XGC,XPixmap);
    int32_t              (*XSetTransientForHint)(XDisplay*,XWindow,XWindow);
    int32_t              (*XSetTSOrigin)(XDisplay*,XGC,int32_t,int32_t);
    int32_t              (*XSetWindowBackground)(XDisplay*,XWindow,uint32_t);
    int32_t              (*XSetWindowBackgroundPixmap)(XDisplay*,XWindow,XPixmap);
    int32_t              (*XSetWindowBorder)(XDisplay*,XWindow,uint32_t);
    int32_t              (*XSetWindowBorderPixmap)(XDisplay*,XWindow,XPixmap);
    int32_t              (*XSetWindowBorderWidth)(XDisplay*,XWindow,uint32_t);
    int32_t              (*XSetWindowColormap)(XDisplay*,XWindow,XColormap);
    int32_t              (*XSetWMColormapWindows)(XDisplay*,XWindow,XWindow*,int32_t);
    int32_t              (*XSetWMProtocols)(XDisplay*,XWindow,XAtom*,int32_t);
    int32_t              (*XStoreBuffer)(XDisplay*,const char*,int32_t,int32_t);
    int32_t              (*XStoreBytes)(XDisplay*,const char*,int32_t);
    int32_t              (*XStoreColor)(XDisplay*,XColormap,XColor*);
    int32_t              (*XStoreColors)(XDisplay*,XColormap,XColor*,int32_t);
    int32_t              (*XStoreName)(XDisplay*,XWindow,const char*);
    int32_t              (*XStoreNamedColor)(XDisplay*,XColormap,const char*,uint32_t,int32_t);
    XKeySym              (*XStringToKeysym)(const char*);
    int32_t              (*XSupportsLocale)();
    int32_t              (*XSync)(XDisplay*,int32_t);
    int32_t              (*XTextExtents)(XFontStruct*,const char*,int32_t,int32_t*,int32_t*,int32_t*,XCharStruct*);
    int32_t              (*XTextExtents16)(XFontStruct*,const XChar2b*,int32_t,int32_t*,int32_t*,int32_t*,XCharStruct*);
    int32_t              (*XTextWidth)(XFontStruct*,const char*,int32_t);
    int32_t              (*XTextWidth16)(XFontStruct*,const XChar2b*,int32_t);
    int32_t              (*XTranslateCoordinates)(XDisplay*,XWindow,XWindow,int32_t,int32_t,int32_t*,int32_t*,XWindow*);
    int32_t              (*XUndefineCursor)(XDisplay*,XWindow);
    int32_t              (*XUngrabButton)(XDisplay*,uint32_t,uint32_t,XWindow);
    int32_t              (*XUngrabKey)(XDisplay*,int32_t,uint32_t,XWindow);
    int32_t              (*XUngrabKeyboard)(XDisplay*,XTime);
    int32_t              (*XUngrabPointer)(XDisplay*,XTime);
    int32_t              (*XUngrabServer)(XDisplay*);
    int32_t              (*XUninstallColormap)(XDisplay*,XColormap);
    int32_t              (*XUnloadFont)(XDisplay*,XFont);
    void                 (*XUnlockDisplay)(XDisplay*);
    int32_t              (*XUnmapSubwindows)(XDisplay*,XWindow);
    int32_t              (*XUnmapWindow)(XDisplay*,XWindow);
    int32_t              (*XUnregisterIMInstantiateCallback)(XDisplay*,XrmHashBucketRec*,char*,char*,XIDProc,void*);
    void                 (*XUnsetICFocus)(XIC);
    void                 (*Xutf8DrawImageString)(XDisplay*,XDrawable,XFontSet,XGC,int32_t,int32_t,const char*,int32_t);
    void                 (*Xutf8DrawString)(XDisplay*,XDrawable,XFontSet,XGC,int32_t,int32_t,const char*,int32_t);
    void                 (*Xutf8DrawText)(XDisplay*,XDrawable,XGC,int32_t,int32_t,XmbTextItem*,int32_t);
    int32_t              (*Xutf8LookupString)(XIC,XKeyEvent*,char*,int32_t,XKeySym*,int32_t*);
    char*                (*Xutf8ResetIC)(XIC);
    int32_t              (*Xutf8TextEscapement)(XFontSet,const char*,int32_t);
    int32_t              (*Xutf8TextExtents)(XFontSet,const char*,int32_t,XRectangle*,XRectangle*);
    int32_t              (*Xutf8TextPerCharExtents)(XFontSet,const char*,int32_t,XRectangle*,XRectangle*,int32_t,int32_t*,XRectangle*,XRectangle*);
    XVaNestedList        (*XVaCreateNestedList)(int32_t,...);
    int32_t              (*XVendorRelease)(XDisplay*);
    XVisualID            (*XVisualIDFromVisual)(XVisual*);
    int32_t              (*XWarpPointer)(XDisplay*,XWindow,XWindow,int32_t,int32_t,uint32_t,uint32_t,int32_t,int32_t);
    void                 (*XwcDrawImageString)(XDisplay*,XDrawable,XFontSet,XGC,int32_t,int32_t,const wchar_t*,int32_t);
    void                 (*XwcDrawString)(XDisplay*,XDrawable,XFontSet,XGC,int32_t,int32_t,const wchar_t*,int32_t);
    void                 (*XwcDrawText)(XDisplay*,XDrawable,XGC,int32_t,int32_t,XwcTextItem*,int32_t);
    int32_t              (*XwcLookupString)(XIC,XKeyEvent*,wchar_t*,int32_t,XKeySym*,int32_t*);
    wchar_t*             (*XwcResetIC)(XIC);
    int32_t              (*XwcTextEscapement)(XFontSet,const wchar_t*,int32_t);
    int32_t              (*XwcTextExtents)(XFontSet,const wchar_t*,int32_t,XRectangle*,XRectangle*);
    int32_t              (*XwcTextPerCharExtents)(XFontSet,const wchar_t*,int32_t,XRectangle*,XRectangle*,int32_t,int32_t*,XRectangle*,XRectangle*);
    uint32_t             (*XWhitePixel)(XDisplay*,int32_t);
    uint32_t             (*XWhitePixelOfScreen)(XScreen*);
    int32_t              (*XWidthMMOfScreen)(XScreen*);
    int32_t              (*XWidthOfScreen)(XScreen*);
    int32_t              (*XWindowEvent)(XDisplay*,XWindow,int32_t,XEvent*);
    int32_t              (*XWithdrawWindow)(XDisplay*,XWindow,int32_t);
    int32_t              (*XWriteBitmapFile)(XDisplay*,const char*,XPixmap,uint32_t,uint32_t,int32_t,int32_t);
    // #include <X11/Xutil.h>
    int32_t              (*XDestroyImage)(XImage*);
    uint32_t             (*XGetPixel)(XImage*,int32_t,int32_t);
    int32_t              (*XPutPixel)(XImage*,int32_t,int32_t,uint32_t);
    XImage*              (*XSubImage)(XImage*,int32_t,int32_t,uint32_t,uint32_t);
    int32_t              (*XAddPixel)(XImage*,int32_t);
    XClassHint*          (*XAllocClassHint)();
    XIconSize*           (*XAllocIconSize)();
    XSizeHints*          (*XAllocSizeHints)();
    XStandardColormap*   (*XAllocStandardColormap)();
    XWMHints*            (*XAllocWMHints)();
    int32_t              (*XClipBox)(XRegion,XRectangle*);
    XRegion              (*XCreateRegion)();
    const char*          (*XDefaultString)();
    int32_t              (*XDeleteContext)(XDisplay*,XID,XContext);
    int32_t              (*XDestroyRegion)(XRegion);
    int                  (*XEmptyRegion)(XRegion);
    int                  (*XEqualRegion)(XRegion,XRegion);
    int32_t              (*XFindContext)(XDisplay*,XID,XContext,void**);
    int                  (*XGetClassHint)(XDisplay*,XWindow,XClassHint*);
    int                  (*XGetIconSizes)(XDisplay*,XWindow,XIconSize**,int32_t*); 
    int                  (*XGetNormalHints)(XDisplay*,XWindow,XSizeHints*); 
    int                  (*XGetRGBColormaps)(XDisplay*,XWindow,XStandardColormap**,int32_t*,XAtom); 
    int                  (*XGetSizeHints)(XDisplay*,XWindow,XSizeHints*,XAtom); 
    int                  (*XGetStandardColormap)(XDisplay*,XWindow,XStandardColormap*,XAtom); 
    int                  (*XGetTextProperty)(XDisplay*,XWindow,XTextProperty*,XAtom); 
    XVisualInfo*         (*XGetVisualInfo)(XDisplay*,int32_t,XVisualInfo*,int32_t*); 
    int                  (*XGetWMClientMachine)(XDisplay*,XWindow,XTextProperty*); 
    XWMHints*            (*XGetWMHints)(XDisplay*,XWindow); 
    int                  (*XGetWMIconName)(XDisplay*,XWindow,XTextProperty*); 
    int                  (*XGetWMName)(XDisplay*,XWindow,XTextProperty*); 
    int                  (*XGetWMNormalHints)(XDisplay*,XWindow,XSizeHints*,int32_t*); 
    int                  (*XGetWMSizeHints)(XDisplay*,XWindow,XSizeHints*,int32_t*,XAtom); 
    int                  (*XGetZoomHints)(XDisplay*,XWindow,XSizeHints*); 
    int32_t              (*XIntersectRegion)(XRegion,XRegion,XRegion); 
    void                 (*XConvertCase)(XKeySym,XKeySym*,XKeySym*); 
    int32_t              (*XLookupString)(XKeyEvent*,char*,int32_t,XKeySym*,XComposeStatus*); 
    int                  (*XMatchVisualInfo)(XDisplay*,int32_t,int32_t,int32_t,XVisualInfo*); 
    int32_t              (*XOffsetRegion)(XRegion,int32_t,int32_t); 
    int                  (*XPointInRegion)(XRegion,int32_t,int32_t); 
    XRegion              (*XPolygonRegion)(XPoint*,int32_t,int32_t); 
    int32_t              (*XRectInRegion)(XRegion,int32_t,int32_t,uint32_t,uint32_t); 
    int32_t              (*XSaveContext)(XDisplay*,XID,XContext,const char*); 
    int32_t              (*XSetClassHint)(XDisplay*,XWindow,XClassHint*); 
    int32_t              (*XSetIconSizes)(XDisplay*,XWindow,XIconSize*,int32_t); 
    int32_t              (*XSetNormalHints)(XDisplay*,XWindow,XSizeHints*); 
    void                 (*XSetRGBColormaps)(XDisplay*,XWindow,XStandardColormap*,int32_t,XAtom); 
    int32_t              (*XSetSizeHints)(XDisplay*,XWindow,XSizeHints*,XAtom); 
    int32_t              (*XSetStandardProperties)(XDisplay*,XWindow,const char*,const char*,XPixmap,char**,int32_t,XSizeHints*); 
    void                 (*XSetTextProperty)(XDisplay*,XWindow,XTextProperty*,XAtom); 
    void                 (*XSetWMClientMachine)(XDisplay*,XWindow,XTextProperty*); 
    int32_t              (*XSetWMHints)(XDisplay*,XWindow,XWMHints*); 
    void                 (*XSetWMIconName)(XDisplay*,XWindow,XTextProperty*); 
    void                 (*XSetWMName)(XDisplay*,XWindow,XTextProperty*); 
    void                 (*XSetWMNormalHints)(XDisplay*,XWindow,XSizeHints*); 
    void                 (*XSetWMProperties)(XDisplay*,XWindow,XTextProperty*,XTextProperty*,char**,int32_t,XSizeHints*,XWMHints*,XClassHint*); 
    void                 (*XmbSetWMProperties)(XDisplay*,XWindow,const char*,const char*,char**,int32_t,XSizeHints*,XWMHints*,XClassHint*); 
    void                 (*Xutf8SetWMProperties)(XDisplay*,XWindow,const char*,const char*,char**,int32_t,XSizeHints*,XWMHints*,XClassHint*); 
    void                 (*XSetWMSizeHints)(XDisplay*,XWindow,XSizeHints*,XAtom); 
    int32_t              (*XSetRegion)(XDisplay*,XGC,XRegion); 
    void                 (*XSetStandardColormap)(XDisplay*,XWindow,XStandardColormap*,XAtom); 
    int32_t              (*XSetZoomHints)(XDisplay*,XWindow,XSizeHints*); 
    int32_t              (*XShrinkRegion)(XRegion,int32_t,int32_t); 
    int                  (*XStringListToTextProperty)(char**,int32_t,XTextProperty*); 
    int32_t              (*XSubtractRegion)(XRegion,XRegion,XRegion); 
    int32_t              (*XmbTextListToTextProperty)(XDisplay*,char**,int32_t,XICCEncodingStyle,XTextProperty*);
    int32_t              (*XwcTextListToTextProperty)(XDisplay*,wchar_t**,int32_t,XICCEncodingStyle,XTextProperty*);
    int32_t              (*Xutf8TextListToTextProperty)(XDisplay*,char**,int32_t,XICCEncodingStyle,XTextProperty*);
    void                 (*XwcFreeStringList)(wchar_t**); 
    int                  (*XTextPropertyToStringList)(XTextProperty*,char***,int32_t*); 
    int32_t              (*XmbTextPropertyToTextList)(XDisplay*,const XTextProperty*,char***,int32_t*); 
    int32_t              (*XwcTextPropertyToTextList)(XDisplay*,const XTextProperty*,wchar_t***,int32_t*); 
    int32_t              (*Xutf8TextPropertyToTextList)(XDisplay*,const XTextProperty*,char***,int32_t*); 
    int32_t              (*XUnionRectWithRegion)(XRectangle*,XRegion,XRegion); 
    int32_t              (*XUnionRegion)(XRegion,XRegion,XRegion); 
    int32_t              (*XWMGeometry)(XDisplay*,int32_t,const char*,const char*,uint32_t,XSizeHints*,int32_t*,int32_t*,int32_t*,int32_t*,int32_t*); 
    int32_t              (*XXorRegion)(XRegion,XRegion,XRegion);
)

// -------------------------------------------------------------------------------------------------------------------------- //
#ifdef __cplusplus
}
#endif
#endif//__core_linux_libX11_h__
// -------------------------------------------------------------------------------------------------------------------------- //