// ┌───────────────────────────────────────────────────────────────────────────────────────────┐
// │ Copyright (c) 2025 Francisco Romano                                                       │
// │                                                                                           │
// │ THIS FILE IS A MODIFIED VERSION OF THE ORIGINAL X WINDOWING SYSTEM (AKA: X11, X) LIBRARY. │
// │ MODIFICATIONS ARE DISTRIBUTED UNDER THE SAME ORIGINAL FILE LICENSE.                       │
// └───────────────────────────────────────────────────────────────────────────────────────────┘

#ifndef _X11_Xatom_h_
#define _X11_Xatom_h_

// THIS IS A GENERATED FILE
// Do not change! Changing this file implies a protocol change!

#define XA_PRIMARY             ((XAtom) 1)
#define XA_SECONDARY           ((XAtom) 2)
#define XA_ARC                 ((XAtom) 3)
#define XA_ATOM                ((XAtom) 4)
#define XA_BITMAP              ((XAtom) 5)
#define XA_CARDINAL            ((XAtom) 6)
#define XA_COLORMAP            ((XAtom) 7)
#define XA_CURSOR              ((XAtom) 8)
#define XA_CUT_BUFFER0         ((XAtom) 9)
#define XA_CUT_BUFFER1         ((XAtom) 10)
#define XA_CUT_BUFFER2         ((XAtom) 11)
#define XA_CUT_BUFFER3         ((XAtom) 12)
#define XA_CUT_BUFFER4         ((XAtom) 13)
#define XA_CUT_BUFFER5         ((XAtom) 14)
#define XA_CUT_BUFFER6         ((XAtom) 15)
#define XA_CUT_BUFFER7         ((XAtom) 16)
#define XA_DRAWABLE            ((XAtom) 17)
#define XA_FONT                ((XAtom) 18)
#define XA_INTEGER             ((XAtom) 19)
#define XA_PIXMAP              ((XAtom) 20)
#define XA_POINT               ((XAtom) 21)
#define XA_RECTANGLE           ((XAtom) 22)
#define XA_RESOURCE_MANAGER    ((XAtom) 23)
#define XA_RGB_COLOR_MAP       ((XAtom) 24)
#define XA_RGB_BEST_MAP        ((XAtom) 25)
#define XA_RGB_BLUE_MAP        ((XAtom) 26)
#define XA_RGB_DEFAULT_MAP     ((XAtom) 27)
#define XA_RGB_GRAY_MAP        ((XAtom) 28)
#define XA_RGB_GREEN_MAP       ((XAtom) 29)
#define XA_RGB_RED_MAP         ((XAtom) 30)
#define XA_STRING              ((XAtom) 31)
#define XA_VISUALID            ((XAtom) 32)
#define XA_WINDOW              ((XAtom) 33)
#define XA_WM_COMMAND          ((XAtom) 34)
#define XA_WM_HINTS            ((XAtom) 35)
#define XA_WM_CLIENT_MACHINE   ((XAtom) 36)
#define XA_WM_ICON_NAME        ((XAtom) 37)
#define XA_WM_ICON_SIZE        ((XAtom) 38)
#define XA_WM_NAME             ((XAtom) 39)
#define XA_WM_NORMAL_HINTS     ((XAtom) 40)
#define XA_WM_SIZE_HINTS       ((XAtom) 41)
#define XA_WM_ZOOM_HINTS       ((XAtom) 42)
#define XA_MIN_SPACE           ((XAtom) 43)
#define XA_NORM_SPACE          ((XAtom) 44)
#define XA_MAX_SPACE           ((XAtom) 45)
#define XA_END_SPACE           ((XAtom) 46)
#define XA_SUPERSCRIPT_X       ((XAtom) 47)
#define XA_SUPERSCRIPT_Y       ((XAtom) 48)
#define XA_SUBSCRIPT_X         ((XAtom) 49)
#define XA_SUBSCRIPT_Y         ((XAtom) 50)
#define XA_UNDERLINE_POSITION  ((XAtom) 51)
#define XA_UNDERLINE_THICKNESS ((XAtom) 52)
#define XA_STRIKEOUT_ASCENT    ((XAtom) 53)
#define XA_STRIKEOUT_DESCENT   ((XAtom) 54)
#define XA_ITALIC_ANGLE        ((XAtom) 55)
#define XA_X_HEIGHT            ((XAtom) 56)
#define XA_QUAD_WIDTH          ((XAtom) 57)
#define XA_WEIGHT              ((XAtom) 58)
#define XA_POINT_SIZE          ((XAtom) 59)
#define XA_RESOLUTION          ((XAtom) 60)
#define XA_COPYRIGHT           ((XAtom) 61)
#define XA_NOTICE              ((XAtom) 62)
#define XA_FONT_NAME           ((XAtom) 63)
#define XA_FAMILY_NAME         ((XAtom) 64)
#define XA_FULL_NAME           ((XAtom) 65)
#define XA_CAP_HEIGHT          ((XAtom) 66)
#define XA_WM_CLASS            ((XAtom) 67)
#define XA_WM_TRANSIENT_FOR    ((XAtom) 68)
#define XA_LAST_PREDEFINED     ((XAtom) 68)

#endif// _X11_Xatom_h_