// -------------------------------------------------------------------------------------------------------------------------- //
// SPDX-License-Identifier: MIT
// Copyright (c) 2024 Francisco Romano
// -------------------------------------------------------------------------------------------------------------------------- //
#include "gles.h"
#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#define LOAD_OPTIONAL_SYMBOL(Name)\
_gles.Name = loader(#Name);\
if (!_gles.Name) { printf("ERROR: failed to load symbol '" #Name "'\n"); }
#define LOAD_REQUIRED_SYMBOL(Name)\
_gles.Name = loader(#Name);\
if (!_gles.Name) { printf("ERROR: failed to load symbol '" #Name "'\n"); return false; }
// -------------------------------------------------------------------------------------------------------------------------- //

struct _gles_impl _gles = { NULL };

bool _free_gles()
{
    // unload and reset library handle
    memset(&_gles, 0, sizeof(struct _gles_impl));
}

bool _load_gles20(void*(*loader)(const char*))
{
    // try loading library and any symbols
    LOAD_REQUIRED_SYMBOL(glActiveTexture)
    LOAD_REQUIRED_SYMBOL(glAttachShader)
    LOAD_REQUIRED_SYMBOL(glBindAttribLocation)
    LOAD_REQUIRED_SYMBOL(glBindBuffer)
    LOAD_REQUIRED_SYMBOL(glBindFramebuffer)
    LOAD_REQUIRED_SYMBOL(glBindRenderbuffer)
    LOAD_REQUIRED_SYMBOL(glBindTexture)
    LOAD_REQUIRED_SYMBOL(glBlendColor)
    LOAD_REQUIRED_SYMBOL(glBlendEquation)
    LOAD_REQUIRED_SYMBOL(glBlendEquationSeparate)
    LOAD_REQUIRED_SYMBOL(glBlendFunc)
    LOAD_REQUIRED_SYMBOL(glBlendFuncSeparate)
    LOAD_REQUIRED_SYMBOL(glBufferData)
    LOAD_REQUIRED_SYMBOL(glBufferSubData)
    LOAD_REQUIRED_SYMBOL(glCheckFramebufferStatus)
    LOAD_REQUIRED_SYMBOL(glClear)
    LOAD_REQUIRED_SYMBOL(glClearColor)
    LOAD_REQUIRED_SYMBOL(glClearDepthf)
    LOAD_REQUIRED_SYMBOL(glClearStencil)
    LOAD_REQUIRED_SYMBOL(glColorMask)
    LOAD_REQUIRED_SYMBOL(glCompileShader)
    LOAD_REQUIRED_SYMBOL(glCompressedTexImage2D)
    LOAD_REQUIRED_SYMBOL(glCompressedTexSubImage2D)
    LOAD_REQUIRED_SYMBOL(glCopyTexImage2D)
    LOAD_REQUIRED_SYMBOL(glCopyTexSubImage2D)
    LOAD_REQUIRED_SYMBOL(glCreateProgram)
    LOAD_REQUIRED_SYMBOL(glCreateShader)
    LOAD_REQUIRED_SYMBOL(glCullFace)
    LOAD_REQUIRED_SYMBOL(glDeleteBuffers)
    LOAD_REQUIRED_SYMBOL(glDeleteFramebuffers)
    LOAD_REQUIRED_SYMBOL(glDeleteProgram)
    LOAD_REQUIRED_SYMBOL(glDeleteRenderbuffers)
    LOAD_REQUIRED_SYMBOL(glDeleteShader)
    LOAD_REQUIRED_SYMBOL(glDeleteTextures)
    LOAD_REQUIRED_SYMBOL(glDepthFunc)
    LOAD_REQUIRED_SYMBOL(glDepthMask)
    LOAD_REQUIRED_SYMBOL(glDepthRangef)
    LOAD_REQUIRED_SYMBOL(glDetachShader)
    LOAD_REQUIRED_SYMBOL(glDisable)
    LOAD_REQUIRED_SYMBOL(glDisableVertexAttribArray)
    LOAD_REQUIRED_SYMBOL(glDrawArrays)
    LOAD_REQUIRED_SYMBOL(glDrawElements)
    LOAD_REQUIRED_SYMBOL(glEnable)
    LOAD_REQUIRED_SYMBOL(glEnableVertexAttribArray)
    LOAD_REQUIRED_SYMBOL(glFinish)
    LOAD_REQUIRED_SYMBOL(glFlush)
    LOAD_REQUIRED_SYMBOL(glFramebufferRenderbuffer)
    LOAD_REQUIRED_SYMBOL(glFramebufferTexture2D)
    LOAD_REQUIRED_SYMBOL(glFrontFace)
    LOAD_REQUIRED_SYMBOL(glGenBuffers)
    LOAD_REQUIRED_SYMBOL(glGenerateMipmap)
    LOAD_REQUIRED_SYMBOL(glGenFramebuffers)
    LOAD_REQUIRED_SYMBOL(glGenRenderbuffers)
    LOAD_REQUIRED_SYMBOL(glGenTextures)
    LOAD_REQUIRED_SYMBOL(glGetActiveAttrib)
    LOAD_REQUIRED_SYMBOL(glGetActiveUniform)
    LOAD_REQUIRED_SYMBOL(glGetAttachedShaders)
    LOAD_REQUIRED_SYMBOL(glGetAttribLocation)
    LOAD_REQUIRED_SYMBOL(glGetBooleanv)
    LOAD_REQUIRED_SYMBOL(glGetBufferParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetError)
    LOAD_REQUIRED_SYMBOL(glGetFloatv)
    LOAD_REQUIRED_SYMBOL(glGetFramebufferAttachmentParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetIntegerv)
    LOAD_REQUIRED_SYMBOL(glGetProgramiv)
    LOAD_REQUIRED_SYMBOL(glGetProgramInfoLog)
    LOAD_REQUIRED_SYMBOL(glGetRenderbufferParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetShaderiv)
    LOAD_REQUIRED_SYMBOL(glGetShaderInfoLog)
    LOAD_REQUIRED_SYMBOL(glGetShaderPrecisionFormat)
    LOAD_REQUIRED_SYMBOL(glGetShaderSource)
    LOAD_REQUIRED_SYMBOL(glGetString)
    LOAD_REQUIRED_SYMBOL(glGetTexParameterfv)
    LOAD_REQUIRED_SYMBOL(glGetTexParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetUniformfv)
    LOAD_REQUIRED_SYMBOL(glGetUniformiv)
    LOAD_REQUIRED_SYMBOL(glGetUniformLocation)
    LOAD_REQUIRED_SYMBOL(glGetVertexAttribfv)
    LOAD_REQUIRED_SYMBOL(glGetVertexAttribiv)
    LOAD_REQUIRED_SYMBOL(glGetVertexAttribPointerv)
    LOAD_REQUIRED_SYMBOL(glHint)
    LOAD_REQUIRED_SYMBOL(glIsBuffer)
    LOAD_REQUIRED_SYMBOL(glIsEnabled)
    LOAD_REQUIRED_SYMBOL(glIsFramebuffer)
    LOAD_REQUIRED_SYMBOL(glIsProgram)
    LOAD_REQUIRED_SYMBOL(glIsRenderbuffer)
    LOAD_REQUIRED_SYMBOL(glIsShader)
    LOAD_REQUIRED_SYMBOL(glIsTexture)
    LOAD_REQUIRED_SYMBOL(glLineWidth)
    LOAD_REQUIRED_SYMBOL(glLinkProgram)
    LOAD_REQUIRED_SYMBOL(glPixelStorei)
    LOAD_REQUIRED_SYMBOL(glPolygonOffset)
    LOAD_REQUIRED_SYMBOL(glReadPixels)
    LOAD_REQUIRED_SYMBOL(glReleaseShaderCompiler)
    LOAD_REQUIRED_SYMBOL(glRenderbufferStorage)
    LOAD_REQUIRED_SYMBOL(glSampleCoverage)
    LOAD_REQUIRED_SYMBOL(glScissor)
    LOAD_REQUIRED_SYMBOL(glShaderBinary)
    LOAD_REQUIRED_SYMBOL(glShaderSource)
    LOAD_REQUIRED_SYMBOL(glStencilFunc)
    LOAD_REQUIRED_SYMBOL(glStencilFuncSeparate)
    LOAD_REQUIRED_SYMBOL(glStencilMask)
    LOAD_REQUIRED_SYMBOL(glStencilMaskSeparate)
    LOAD_REQUIRED_SYMBOL(glStencilOp)
    LOAD_REQUIRED_SYMBOL(glStencilOpSeparate)
    LOAD_REQUIRED_SYMBOL(glTexImage2D)
    LOAD_REQUIRED_SYMBOL(glTexParameterf)
    LOAD_REQUIRED_SYMBOL(glTexParameterfv)
    LOAD_REQUIRED_SYMBOL(glTexParameteri)
    LOAD_REQUIRED_SYMBOL(glTexParameteriv)
    LOAD_REQUIRED_SYMBOL(glTexSubImage2D)
    LOAD_REQUIRED_SYMBOL(glUniform1f)
    LOAD_REQUIRED_SYMBOL(glUniform1fv)
    LOAD_REQUIRED_SYMBOL(glUniform1i)
    LOAD_REQUIRED_SYMBOL(glUniform1iv)
    LOAD_REQUIRED_SYMBOL(glUniform2f)
    LOAD_REQUIRED_SYMBOL(glUniform2fv)
    LOAD_REQUIRED_SYMBOL(glUniform2i)
    LOAD_REQUIRED_SYMBOL(glUniform2iv)
    LOAD_REQUIRED_SYMBOL(glUniform3f)
    LOAD_REQUIRED_SYMBOL(glUniform3fv)
    LOAD_REQUIRED_SYMBOL(glUniform3i)
    LOAD_REQUIRED_SYMBOL(glUniform3iv)
    LOAD_REQUIRED_SYMBOL(glUniform4f)
    LOAD_REQUIRED_SYMBOL(glUniform4fv)
    LOAD_REQUIRED_SYMBOL(glUniform4i)
    LOAD_REQUIRED_SYMBOL(glUniform4iv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix2fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix3fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix4fv)
    LOAD_REQUIRED_SYMBOL(glUseProgram)
    LOAD_REQUIRED_SYMBOL(glValidateProgram)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib1f)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib1fv)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib2f)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib2fv)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib3f)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib3fv)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib4f)
    LOAD_REQUIRED_SYMBOL(glVertexAttrib4fv)
    LOAD_REQUIRED_SYMBOL(glVertexAttribPointer)
    LOAD_REQUIRED_SYMBOL(glViewport)
    return true;
}

bool _load_gles30(void*(*loader)(const char*))
{
    // try loading library and any symbols
    LOAD_REQUIRED_SYMBOL(glReadBuffer)
    LOAD_REQUIRED_SYMBOL(glDrawRangeElements)
    LOAD_REQUIRED_SYMBOL(glTexImage3D)
    LOAD_REQUIRED_SYMBOL(glTexSubImage3D)
    LOAD_REQUIRED_SYMBOL(glCopyTexSubImage3D)
    LOAD_REQUIRED_SYMBOL(glCompressedTexImage3D)
    LOAD_REQUIRED_SYMBOL(glCompressedTexSubImage3D)
    LOAD_REQUIRED_SYMBOL(glGenQueries)
    LOAD_REQUIRED_SYMBOL(glDeleteQueries)
    LOAD_REQUIRED_SYMBOL(glIsQuery)
    LOAD_REQUIRED_SYMBOL(glBeginQuery)
    LOAD_REQUIRED_SYMBOL(glEndQuery)
    LOAD_REQUIRED_SYMBOL(glGetQueryiv)
    LOAD_REQUIRED_SYMBOL(glGetQueryObjectuiv)
    LOAD_REQUIRED_SYMBOL(glUnmapBuffer)
    LOAD_REQUIRED_SYMBOL(glGetBufferPointerv)
    LOAD_REQUIRED_SYMBOL(glDrawBuffers)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix2x3fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix3x2fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix2x4fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix4x2fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix3x4fv)
    LOAD_REQUIRED_SYMBOL(glUniformMatrix4x3fv)
    LOAD_REQUIRED_SYMBOL(glBlitFramebuffer)
    LOAD_REQUIRED_SYMBOL(glRenderbufferStorageMultisample)
    LOAD_REQUIRED_SYMBOL(glFramebufferTextureLayer)
    LOAD_REQUIRED_SYMBOL(glMapBufferRange)
    LOAD_REQUIRED_SYMBOL(glFlushMappedBufferRange)
    LOAD_REQUIRED_SYMBOL(glBindVertexArray)
    LOAD_REQUIRED_SYMBOL(glDeleteVertexArrays)
    LOAD_REQUIRED_SYMBOL(glGenVertexArrays)
    LOAD_REQUIRED_SYMBOL(glIsVertexArray)
    LOAD_REQUIRED_SYMBOL(glGetIntegeri_v)
    LOAD_REQUIRED_SYMBOL(glBeginTransformFeedback)
    LOAD_REQUIRED_SYMBOL(glEndTransformFeedback)
    LOAD_REQUIRED_SYMBOL(glBindBufferRange)
    LOAD_REQUIRED_SYMBOL(glBindBufferBase)
    LOAD_REQUIRED_SYMBOL(glTransformFeedbackVaryings)
    LOAD_REQUIRED_SYMBOL(glGetTransformFeedbackVarying)
    LOAD_REQUIRED_SYMBOL(glVertexAttribIPointer)
    LOAD_REQUIRED_SYMBOL(glGetVertexAttribIiv)
    LOAD_REQUIRED_SYMBOL(glGetVertexAttribIuiv)
    LOAD_REQUIRED_SYMBOL(glVertexAttribI4i)
    LOAD_REQUIRED_SYMBOL(glVertexAttribI4ui)
    LOAD_REQUIRED_SYMBOL(glVertexAttribI4iv)
    LOAD_REQUIRED_SYMBOL(glVertexAttribI4uiv)
    LOAD_REQUIRED_SYMBOL(glGetUniformuiv)
    LOAD_REQUIRED_SYMBOL(glGetFragDataLocation)
    LOAD_REQUIRED_SYMBOL(glUniform1ui)
    LOAD_REQUIRED_SYMBOL(glUniform2ui)
    LOAD_REQUIRED_SYMBOL(glUniform3ui)
    LOAD_REQUIRED_SYMBOL(glUniform4ui)
    LOAD_REQUIRED_SYMBOL(glUniform1uiv)
    LOAD_REQUIRED_SYMBOL(glUniform2uiv)
    LOAD_REQUIRED_SYMBOL(glUniform3uiv)
    LOAD_REQUIRED_SYMBOL(glUniform4uiv)
    LOAD_REQUIRED_SYMBOL(glClearBufferiv)
    LOAD_REQUIRED_SYMBOL(glClearBufferuiv)
    LOAD_REQUIRED_SYMBOL(glClearBufferfv)
    LOAD_REQUIRED_SYMBOL(glClearBufferfi)
    LOAD_REQUIRED_SYMBOL(glGetStringi)
    LOAD_REQUIRED_SYMBOL(glCopyBufferSubData)
    LOAD_REQUIRED_SYMBOL(glGetUniformIndices)
    LOAD_REQUIRED_SYMBOL(glGetActiveUniformsiv)
    LOAD_REQUIRED_SYMBOL(glGetUniformBlockIndex)
    LOAD_REQUIRED_SYMBOL(glGetActiveUniformBlockiv)
    LOAD_REQUIRED_SYMBOL(glGetActiveUniformBlockName)
    LOAD_REQUIRED_SYMBOL(glUniformBlockBinding)
    LOAD_REQUIRED_SYMBOL(glDrawArraysInstanced)
    LOAD_REQUIRED_SYMBOL(glDrawElementsInstanced)
    LOAD_REQUIRED_SYMBOL(glFenceSync)
    LOAD_REQUIRED_SYMBOL(glIsSync)
    LOAD_REQUIRED_SYMBOL(glDeleteSync)
    LOAD_REQUIRED_SYMBOL(glClientWaitSync)
    LOAD_REQUIRED_SYMBOL(glWaitSync)
    LOAD_REQUIRED_SYMBOL(glGetInteger64v)
    LOAD_REQUIRED_SYMBOL(glGetSynciv)
    LOAD_REQUIRED_SYMBOL(glGetInteger64i_v)
    LOAD_REQUIRED_SYMBOL(glGetBufferParameteri64v)
    LOAD_REQUIRED_SYMBOL(glGenSamplers)
    LOAD_REQUIRED_SYMBOL(glDeleteSamplers)
    LOAD_REQUIRED_SYMBOL(glIsSampler)
    LOAD_REQUIRED_SYMBOL(glBindSampler)
    LOAD_REQUIRED_SYMBOL(glSamplerParameteri)
    LOAD_REQUIRED_SYMBOL(glSamplerParameteriv)
    LOAD_REQUIRED_SYMBOL(glSamplerParameterf)
    LOAD_REQUIRED_SYMBOL(glSamplerParameterfv)
    LOAD_REQUIRED_SYMBOL(glGetSamplerParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetSamplerParameterfv)
    LOAD_REQUIRED_SYMBOL(glVertexAttribDivisor)
    LOAD_REQUIRED_SYMBOL(glBindTransformFeedback)
    LOAD_REQUIRED_SYMBOL(glDeleteTransformFeedbacks)
    LOAD_REQUIRED_SYMBOL(glGenTransformFeedbacks)
    LOAD_REQUIRED_SYMBOL(glIsTransformFeedback)
    LOAD_REQUIRED_SYMBOL(glPauseTransformFeedback)
    LOAD_REQUIRED_SYMBOL(glResumeTransformFeedback)
    LOAD_REQUIRED_SYMBOL(glGetProgramBinary)
    LOAD_REQUIRED_SYMBOL(glProgramBinary)
    LOAD_REQUIRED_SYMBOL(glProgramParameteri)
    LOAD_REQUIRED_SYMBOL(glInvalidateFramebuffer)
    LOAD_REQUIRED_SYMBOL(glInvalidateSubFramebuffer)
    LOAD_REQUIRED_SYMBOL(glTexStorage2D)
    LOAD_REQUIRED_SYMBOL(glTexStorage3D)
    LOAD_REQUIRED_SYMBOL(glGetInternalformativ)
    return true;
}

bool _load_gles31(void*(*loader)(const char*))
{
    // try loading library and any symbols
    LOAD_REQUIRED_SYMBOL(glDispatchCompute)
    LOAD_REQUIRED_SYMBOL(glDispatchComputeIndirect)
    LOAD_REQUIRED_SYMBOL(glDrawArraysIndirect)
    LOAD_REQUIRED_SYMBOL(glDrawElementsIndirect)
    LOAD_REQUIRED_SYMBOL(glFramebufferParameteri)
    LOAD_REQUIRED_SYMBOL(glGetFramebufferParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetProgramInterfaceiv)
    LOAD_REQUIRED_SYMBOL(glGetProgramResourceIndex)
    LOAD_REQUIRED_SYMBOL(glGetProgramResourceName)
    LOAD_REQUIRED_SYMBOL(glGetProgramResourceiv)
    LOAD_REQUIRED_SYMBOL(glGetProgramResourceLocation)
    LOAD_REQUIRED_SYMBOL(glUseProgramStages)
    LOAD_REQUIRED_SYMBOL(glActiveShaderProgram)
    LOAD_REQUIRED_SYMBOL(glCreateShaderProgramv)
    LOAD_REQUIRED_SYMBOL(glBindProgramPipeline)
    LOAD_REQUIRED_SYMBOL(glDeleteProgramPipelines)
    LOAD_REQUIRED_SYMBOL(glGenProgramPipelines)
    LOAD_REQUIRED_SYMBOL(glIsProgramPipeline)
    LOAD_REQUIRED_SYMBOL(glGetProgramPipelineiv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform1i)
    LOAD_REQUIRED_SYMBOL(glProgramUniform2i)
    LOAD_REQUIRED_SYMBOL(glProgramUniform3i)
    LOAD_REQUIRED_SYMBOL(glProgramUniform4i)
    LOAD_REQUIRED_SYMBOL(glProgramUniform1ui)
    LOAD_REQUIRED_SYMBOL(glProgramUniform2ui)
    LOAD_REQUIRED_SYMBOL(glProgramUniform3ui)
    LOAD_REQUIRED_SYMBOL(glProgramUniform4ui)
    LOAD_REQUIRED_SYMBOL(glProgramUniform1f)
    LOAD_REQUIRED_SYMBOL(glProgramUniform2f)
    LOAD_REQUIRED_SYMBOL(glProgramUniform3f)
    LOAD_REQUIRED_SYMBOL(glProgramUniform4f)
    LOAD_REQUIRED_SYMBOL(glProgramUniform1iv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform2iv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform3iv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform4iv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform1uiv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform2uiv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform3uiv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform4uiv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform1fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform2fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform3fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniform4fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix2fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix3fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix4fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix2x3fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix3x2fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix2x4fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix4x2fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix3x4fv)
    LOAD_REQUIRED_SYMBOL(glProgramUniformMatrix4x3fv)
    LOAD_REQUIRED_SYMBOL(glValidateProgramPipeline)
    LOAD_REQUIRED_SYMBOL(glGetProgramPipelineInfoLog)
    LOAD_REQUIRED_SYMBOL(glBindImageTexture)
    LOAD_REQUIRED_SYMBOL(glGetBooleani_v)
    LOAD_REQUIRED_SYMBOL(glMemoryBarrier)
    LOAD_REQUIRED_SYMBOL(glMemoryBarrierByRegion)
    LOAD_REQUIRED_SYMBOL(glTexStorage2DMultisample)
    LOAD_REQUIRED_SYMBOL(glGetMultisamplefv)
    LOAD_REQUIRED_SYMBOL(glSampleMaski)
    LOAD_REQUIRED_SYMBOL(glGetTexLevelParameteriv)
    LOAD_REQUIRED_SYMBOL(glGetTexLevelParameterfv)
    LOAD_REQUIRED_SYMBOL(glBindVertexBuffer)
    LOAD_REQUIRED_SYMBOL(glVertexAttribFormat)
    LOAD_REQUIRED_SYMBOL(glVertexAttribIFormat)
    LOAD_REQUIRED_SYMBOL(glVertexAttribBinding)
    LOAD_REQUIRED_SYMBOL(glVertexBindingDivisor)
    return true;
}

bool _load_gles32(void*(*loader)(const char*))
{
    // try loading library and any symbols
    LOAD_OPTIONAL_SYMBOL(glBlendBarrier)
    LOAD_REQUIRED_SYMBOL(glCopyImageSubData)
    LOAD_REQUIRED_SYMBOL(glDebugMessageControl)
    LOAD_REQUIRED_SYMBOL(glDebugMessageInsert)
    LOAD_REQUIRED_SYMBOL(glDebugMessageCallback)
    LOAD_REQUIRED_SYMBOL(glGetDebugMessageLog)
    LOAD_REQUIRED_SYMBOL(glPushDebugGroup)
    LOAD_REQUIRED_SYMBOL(glPopDebugGroup)
    LOAD_REQUIRED_SYMBOL(glObjectLabel)
    LOAD_REQUIRED_SYMBOL(glGetObjectLabel)
    LOAD_REQUIRED_SYMBOL(glObjectPtrLabel)
    LOAD_REQUIRED_SYMBOL(glGetObjectPtrLabel)
    LOAD_REQUIRED_SYMBOL(glGetPointerv)
    LOAD_REQUIRED_SYMBOL(glEnablei)
    LOAD_REQUIRED_SYMBOL(glDisablei)
    LOAD_REQUIRED_SYMBOL(glBlendEquationi)
    LOAD_REQUIRED_SYMBOL(glBlendEquationSeparatei)
    LOAD_REQUIRED_SYMBOL(glBlendFunci)
    LOAD_REQUIRED_SYMBOL(glBlendFuncSeparatei)
    LOAD_REQUIRED_SYMBOL(glColorMaski)
    LOAD_REQUIRED_SYMBOL(glIsEnabledi)
    LOAD_REQUIRED_SYMBOL(glDrawElementsBaseVertex)
    LOAD_REQUIRED_SYMBOL(glDrawRangeElementsBaseVertex)
    LOAD_REQUIRED_SYMBOL(glDrawElementsInstancedBaseVertex)
    LOAD_REQUIRED_SYMBOL(glFramebufferTexture)
    LOAD_OPTIONAL_SYMBOL(glPrimitiveBoundingBox)
    LOAD_REQUIRED_SYMBOL(glGetGraphicsResetStatus)
    LOAD_REQUIRED_SYMBOL(glReadnPixels)
    LOAD_REQUIRED_SYMBOL(glGetnUniformfv)
    LOAD_REQUIRED_SYMBOL(glGetnUniformiv)
    LOAD_REQUIRED_SYMBOL(glGetnUniformuiv)
    LOAD_REQUIRED_SYMBOL(glMinSampleShading)
    LOAD_REQUIRED_SYMBOL(glPatchParameteri)
    LOAD_REQUIRED_SYMBOL(glTexParameterIiv)
    LOAD_REQUIRED_SYMBOL(glTexParameterIuiv)
    LOAD_REQUIRED_SYMBOL(glGetTexParameterIiv)
    LOAD_REQUIRED_SYMBOL(glGetTexParameterIuiv)
    LOAD_REQUIRED_SYMBOL(glSamplerParameterIiv)
    LOAD_REQUIRED_SYMBOL(glSamplerParameterIuiv)
    LOAD_REQUIRED_SYMBOL(glGetSamplerParameterIiv)
    LOAD_REQUIRED_SYMBOL(glGetSamplerParameterIuiv)
    LOAD_REQUIRED_SYMBOL(glTexBuffer)
    LOAD_REQUIRED_SYMBOL(glTexBufferRange)
    LOAD_REQUIRED_SYMBOL(glTexStorage3DMultisample)
    return true;
}

bool _load_gles(void*(*loader)(const char*))
{
    // try loading OpenGL ES 2.0 symbols
    if (!_load_gles20(loader)) return false;

    // try loading OpenGL ES 3.0 symbols
    if (!_load_gles30(loader))
    {
        printf("WARNING: loaded library 'gles20'\n");
        return true;
    }

    // try loading OpenGL ES 3.1 symbols
    if (!_load_gles31(loader))
    {
        printf("WARNING: loaded library 'gles30'\n");
        return true;
    }

    // try loading OpenGL ES 3.2 symbols
    if (!_load_gles32(loader))
    {
        printf("WARNING: loaded library 'gles31'\n");
        return true;
    }

    printf("WARNING: loaded library 'gles32'\n");
    return true;
}

// -------------------------------------------------------------------------------------------------------------------------- //